on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
      - requested

name: Check Annotations

jobs:
  annotations:
    name: Annotations
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-actions
      - name: Download Annotations
        id: annotations
        uses: ./
        with:
          INCLUDE_LEVELS: warning
      - name: Build attachments
        run: echo "SLACK_ATTACHMENTS=$(echo '${{ steps.annotations.outputs.messages }}' | jq -c 'map({"color":"warning","text":.})')" >> $GITHUB_ENV
        if: steps.annotations.outputs.number > 0
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "Warning annotations",
              attachments: ${{ env.SLACK_ATTACHMENTS }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: steps.annotations.outputs.number > 0 && env.SLACK_WEBHOOK_URL
